//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// Runtime Version:2.0.50727.42
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using JPB.DataAccess.AdoWrapper;
using JPB.DataAccess;
using JPB.DataAccess.ModelsAnotations;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using JPB.DataAccess.DbInfoConfig;
using JPB.DataAccess.EntityCollections;

namespace JPB.InhousePlayback.Server.Services.Database.Models
{


	[GeneratedCodeAttribute(tool: "JPB.DataAccess.EntityCreator.MsSql.MsSqlCreator", version: "2.0.0.0")]
	public partial class Season
	{
		public Season() {}
		public int SeasonId  { get; set; }
		public string Name  { get; set; }
		public string Location  { get; set; }
		public Nullable<Int32> PlaybackLength  { get; set; }
		public Nullable<Int32> OffsetStart  { get; set; }
		public Nullable<Int32> OffsetEnd  { get; set; }
		public int OrderNo  { get; set; }
		public int IdGenre  { get; set; }
		public virtual Genre Genre  { get; set; }
		public virtual DbCollection<Title> Title  { get; set; }
		public static Season Factory(EagarDataRecord reader)
		{
			var super = new Season();
			super.SeasonId = (int)reader["SeasonId"];
			super.Name = (string)reader["Name"];
			super.Location = (string)reader["Location"];
			super.PlaybackLength = (Nullable<Int32>)reader["PlaybackLength"];
			super.OffsetStart = (Nullable<Int32>)reader["OffsetStart"];
			super.OffsetEnd = (Nullable<Int32>)reader["OffsetEnd"];
			super.OrderNo = (int)reader["OrderNo"];
			super.IdGenre = (int)reader["IdGenre"];
			var readersOfGenre = ((EagarDataRecord[])reader["Genre"])?.FirstOrDefault();
			super.Genre = readersOfGenre == null ? null : ((Genre)(typeof(Genre).GetClassInfo().SetPropertiesViaReflection(reader: readersOfGenre)));
			var readersOfTitle = ((EagarDataRecord[])reader["Title"]);
			super.Title = readersOfTitle == null ? null : new DbCollection<Title>(readersOfTitle.Select(item => ((Title)(typeof(Title).GetClassInfo().SetPropertiesViaReflection(reader: item)))));
			return super;
		}
		static partial void BeforeConfig();
		static partial void AfterConfig();
		static partial void BeforeConfig(ConfigurationResolver<Season> config);
		static partial void AfterConfig(ConfigurationResolver<Season> config);
		[ConfigMehtodAttribute]
		public static void Configuration(ConfigurationResolver<Season> config)
		{
			BeforeConfig();
			BeforeConfig(config);
			config.SetPropertyAttribute(s => s.SeasonId, new PrimaryKeyAttribute());
			config.SetPropertyAttribute(s => s.IdGenre, new ForeignKeyDeclarationAttribute(foreignKey: "GenreId", foreignTable: typeof(Genre)));
			config.SetPropertyAttribute(s => s.Genre, new ForeignKeyAttribute(foreignKey: "IdGenre", referenceKey: "GenreId"));
			config.SetPropertyAttribute(s => s.Title, new ForeignKeyAttribute(referenceKey: "IdSeason", foreignKey: "SeasonId"));
			AfterConfig(config);
			AfterConfig();
		}
	}
}
